# -*- coding: utf-8 -*-
"""Rohan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dykvo_JRciGEKqzfuI7aanWSvITk3fXK
"""

a=5
print(a)

